- name: Play 1 Create the Demo Tenant
  hosts: all
  gather_facts: no
######

  tasks:

   - set_fact:
      aci_login: &aci_login
        host: "{{ inventory_hostname }}"
        username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
        password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
        use_ssl: yes
        validate_certs: no


   - name: Add {{ tenant_name }} tenant
     aci_tenant:
       <<: *aci_login
       tenant: "{{ tenant_name }}"
       description: Production tenant
       state: present
     delegate_to: localhost
      
      ######### Tenant Config ##########
#   - name: Set {{ tenant_name }} Tenant
#     aci_tenant:
#       <<: *aci_login
#       state: present
#       tenant: "{{ tenant_name }}"
#     delegate_to: localhost
